
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enrollement
    username: valeria
    password: 'post456'
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        lob:
          non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: 'public'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
server:
  port: 8081

#docker run -d --name=grafana -p 3000:3000 grafana/grafana
# docker run -d --name=prometheus -p 9090:9090 -v /Users/snoleopard/Documents/javaprojects/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus --config.file=/etc/prometheus/prometheus.yml